

# The following file is released under the Apache 2 Licence, see LICENCE.txx

# The following file is release under the Apache 2 Licence, see LICENCE.txx

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf